---
title: "RepData_PeerAssessment1"
output: html_document
---

# Reproducible Research
## Peer-graded Assignment: Course Project 1
### Robert Miller
### March 7, 2017

### Loading and preprocessing data
```{r code for reading in dataset}
library(ggplot2)

rawdevicedata<-read.csv("activity.csv")

devicedata<-rawdevicedata

# initial parse/validation of data
head(devicedata)
dim(devicedata)

n1<-nrow(devicedata)

# remove NA values
devicedata<-devicedata[complete.cases(devicedata),]

n2<-nrow(devicedata)

# post processing parse/validation of data
head(devicedata)
dim(devicedata)

print(paste0("Rows removed from dataset: ",n1-n2,"."))

# set type for date to Date
devicedata$date<-as.Date(devicedata$date)

```
### Histogram of processed data
```{r histogram of total number of steps}

plot(y=devicedata$steps,x=devicedata$date,type="h",
     xlab="Date",ylab="Number of Steps",
     main="Number of Steps per Day Oct. 1 to Dec. 1 2012")

  
```

### Mean and Median Steps Per Day
```{r mean/median steps}


meandevicedata<-as.data.frame(unique(devicedata$date))

for(i in 1:nrow(meandevicedata)){
    temp<-mean(devicedata[devicedata$date==meandevicedata[i,1],
                          "steps"])
    meandevicedata[i,2]<-temp
}

names(meandevicedata)<-c("date","mean_steps")

mediandevicedata<-as.data.frame(unique(devicedata$date))

for(i in 1:nrow(mediandevicedata)){
    temp<-median(devicedata[devicedata$date==mediandevicedata[i,1],
                            "steps"])
    mediandevicedata[i,2]<-temp
}

names(mediandevicedata)<-c("date","median_steps")


plot(y=meandevicedata$mean_steps,x=meandevicedata$date,
     type="h",
     xlab="Date",ylab="Mean Number of Steps",
     main="Mean Steps per Day Oct. 1 to Dec. 1 2012")

plot(y=mediandevicedata$median_steps,x=mediandevicedata$date,
     type="h",
     xlab="Date",ylab="Median Number of Steps",
     main="Median Steps per Day Oct. 1 to Dec. 1 2012")

```

### Average Steps Time Series Plot
```{r time series plot}
plot(meandevicedata,type="l",ylab="Mean Steps",
     xlab="Date",
     main="Average Number of Steps Per Day")
```

### Data Imputation
```{r data imputation}

```

### Nacho Cheese Doritos